# Specify the version of Docker Compose
version: '3'

# Specify types of container (services) that will be created when run 'docker-compose up'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - /home/luisruivo/frontend:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - /home/luisruivo/frontend:/home/node/app
    command: ["npm", "test"]