# name: Docker Build, Push, and Deploy

# on:
#   push:
#     branches:
#       - main  # Change this to the branch you want to trigger the workflow on

# jobs:
#   build-push-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Login to Docker Hub
      
#         uses: docker/login-action@v2.1.0
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and Push Docker Images
#         uses: docker/build-push-action@v4.0.0

#         with:
#           context: .
#           push: true
#           tags: docker:v1

#           run: docker push ramiahm/docker-react:latest
   

name: Deploy to test server

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:

    build-frontend-and-push:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Docker Login
          uses: docker/login-action@v2.1.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            

        - name: Build and push Docker images
          uses: docker/build-push-action@v4.0.0
          with:
             context: .
             push: true
             tags: ramiahm/docker-react:v1